version: '3.8'
services:
  ct-technitium:
    image: technitium/dns-server:latest
    container_name: ct-technitium
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5380:5380/tcp"
    volumes:
      - /etc/dns:/etc/dns
    restart: always
    cap_add:
      - NET_ADMIN